<?xml version="1.0"?>
<package format="2">
  <name>urdf_juggle</name>
  <version>0.4.0</version>
  <description>Helpfull Xacro macroses for URDF</description>

  <maintainer email="standmit@yandex.ru">Andrey Stepanov</maintainer>

  <license>MIT</license>

  <author email="standmit@yandex.ru">Andrey Stepanov</author>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
</package>
